
(function(){
'use strict';
const MANIFEST=JSON.parse(document.getElementById('v080ReviewManifest').textContent);
const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const safeId=id=>{try{return document.getElementById(id)}catch{return null}};
function runReview(){
 const errors=[],warnings=[];const exp=MANIFEST.expected;
 const fig=qa('.figure-card[id]').map(x=>x.id),tables=qa('.table-card[id]').map(x=>x.id),buttons=qa('.figure-study-button');
 if(fig.length!==exp.figure_cards)errors.push(`figure_cards:${fig.length}/${exp.figure_cards}`);
 if(tables.length!==exp.table_cards)errors.push(`table_cards:${tables.length}/${exp.table_cards}`);
 if(buttons.length!==exp.study_buttons)errors.push(`study_buttons:${buttons.length}/${exp.study_buttons}`);
 if(JSON.stringify(fig)!==JSON.stringify(exp.figure_ids))errors.push('figure_id_order');
 if(JSON.stringify(tables)!==JSON.stringify(exp.table_ids))errors.push('table_id_order');
 for(const id of exp.study_ids){const card=safeId(id),n=card?.querySelectorAll('.figure-study-button').length||0;if(n!==1)errors.push(`study_entry:${id}:${n}`);}
 for(const id of exp.table_ids){if(safeId(id)?.querySelector('.figure-study-button'))errors.push(`table_study_entry:${id}`);}
 qa('.figure-ref,.open-in-viewer').forEach((el,i)=>{const raw=el.dataset.targets||el.dataset.target||'';raw.split(',').map(x=>x.trim()).filter(Boolean).forEach(id=>{if(!safeId(id))errors.push(`broken_ref:${i}:${id}`)})});
 qa('.v6-asset-card[data-target]').forEach((el,i)=>{const id=el.dataset.target;if(!safeId(id))errors.push(`broken_preview:${i}:${id}`);const n=el.querySelectorAll('.v6-study-open').length;if(n>1)errors.push(`duplicate_preview_study:${id}`);if(n===1&&!exp.study_ids.includes(id))errors.push(`invalid_preview_study:${id}`);});
 const verified=MANIFEST.panel_location_policy.verified_panel_maps||{};
 Object.entries(verified).forEach(([id,maps])=>{if(!exp.study_ids.includes(id))errors.push(`hotspot_unknown_figure:${id}`);(maps||[]).forEach((m,j)=>{if(m.verified!==true)errors.push(`hotspot_unverified:${id}:${j}`);for(const k of ['x','y','w','h'])if(!(Number.isFinite(m[k])&&m[k]>=0&&m[k]<=1))errors.push(`hotspot_bounds:${id}:${j}:${k}`);})});
 if(Object.keys(verified).length===0)warnings.push('image_panel_focus_disabled_without_verified_coordinates');
 const report={version:MANIFEST.version,passed:errors.length===0,errors,warnings,checkedAt:new Date().toISOString()};
 window.__CANVAS_V080_REVIEW__=report;document.documentElement.dataset.v080Review=report.passed?'passed':'failed';document.documentElement.classList.toggle('v080-review-failed',!report.passed);
 if(!report.passed)console.error('[CANVAS V0.8 review failed]',report);
 return report;
}
function motion(){document.body.classList.add('v080-layout-motion');clearTimeout(motion.t);motion.t=setTimeout(()=>document.body.classList.remove('v080-layout-motion'),520)}
function installMotionHooks(){document.addEventListener('click',e=>{if(e.target.closest('#tocBtn,#viewerClose,#viewerEdgeReveal,#annotationBtn,#annotationDrawerClose,#settingsBtn,#settingsClose,.figure-ref,.open-in-viewer,.v6-asset-card,.figure-study-button,.v6-study-open,#viewerStudyLaunchV077,#v6StudyClose'))motion()},true)}
let searchPanel=null,lastMark=null,searchResults=[];
function categoryFor(node){const p=node.parentElement;if(p.closest('.source-block'))return'英文正文';if(p.closest('.translation-block,.translation-content'))return'中文翻译';if(p.closest('.caption-en'))return'英文图注';if(p.closest('.caption-zh,.bilingual-caption'))return'中文图注';if(p.closest('.figure-card,.table-card'))return'图表内容';if(p.closest('.hero'))return'论文信息';return'正文与方法';}
function labelFor(node){const block=node.parentElement.closest('[data-annotation-block],.bilingual-unit,.paper-section,.figure-card,.table-card,.hero');return block?.querySelector('h2,h3,.figure-heading span')?.textContent?.trim()||block?.id||''}
function cleanMark(){if(lastMark?.isConnected){const t=document.createTextNode(lastMark.textContent);lastMark.replaceWith(t);t.parentNode?.normalize()}lastMark=null}
function locateResult(item){cleanMark();let n=item.node;if(!n?.isConnected)return;const value=n.nodeValue||'',idx=value.toLocaleLowerCase().indexOf(item.term.toLocaleLowerCase());if(idx<0)return;const before=n.splitText(idx),after=before.splitText(item.term.length);const mark=document.createElement('mark');mark.className='v080-search-hit';mark.textContent=before.nodeValue;before.replaceWith(mark);lastMark=mark;const block=mark.closest('[data-annotation-block],.bilingual-unit,.paper-section,.figure-card,.table-card,.hero')||mark.parentElement;block?.classList.add('v080-locate-flash');mark.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>block?.classList.remove('v080-locate-flash'),1600);setTimeout(cleanMark,6000);closeSearch();}
function closeSearch(){searchPanel?.classList.remove('open')}
function buildSearch(term){cleanMark();searchResults=[];const pane=q('#bilingual-pane');if(!pane||!term)return;const low=term.toLocaleLowerCase(),walker=document.createTreeWalker(pane,NodeFilter.SHOW_TEXT,{acceptNode(n){if(!n.nodeValue?.trim()||!n.nodeValue.toLocaleLowerCase().includes(low))return NodeFilter.FILTER_REJECT;const p=n.parentElement;if(!p||p.closest('script,style,button,select,textarea,.term-tooltip,.reference-popover'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT;}});while(walker.nextNode()&&searchResults.length<160){const n=walker.currentNode,raw=n.nodeValue.replace(/\s+/g,' ').trim(),at=raw.toLocaleLowerCase().indexOf(low);const start=Math.max(0,at-46),end=Math.min(raw.length,at+term.length+72);searchResults.push({node:n,term,category:categoryFor(n),label:labelFor(n),snippet:(start?'…':'')+raw.slice(start,end)+(end<raw.length?'…':'')})}renderSearch(term)}
function renderSearch(term){if(!searchPanel){searchPanel=document.createElement('section');searchPanel.className='v080-search-panel';searchPanel.setAttribute('aria-label','分类搜索结果');document.body.append(searchPanel)}const groups=new Map;searchResults.forEach(x=>{if(!groups.has(x.category))groups.set(x.category,[]);groups.get(x.category).push(x)});searchPanel.innerHTML='<div class="v080-search-head"><strong></strong><button type="button" aria-label="关闭">×</button></div><div class="v080-search-body"></div>';q('strong',searchPanel).textContent=`“${term}” · ${searchResults.length}处`;q('button',searchPanel).onclick=closeSearch;const body=q('.v080-search-body',searchPanel);if(!searchResults.length)body.innerHTML='<div class="v080-search-group">当前双语正文中没有匹配内容。</div>';groups.forEach((items,name)=>{const sec=document.createElement('section');sec.className='v080-search-group';const h=document.createElement('h3');h.textContent=`${name}（${items.length}）`;sec.append(h);items.slice(0,40).forEach(item=>{const b=document.createElement('button');b.type='button';b.className='v080-search-result';b.innerHTML='<span></span><small></small>';q('span',b).textContent=item.snippet;q('small',b).textContent=item.label;b.onclick=()=>locateResult(item);sec.append(b)});body.append(sec)});requestAnimationFrame(()=>searchPanel.classList.add('open'))}
function installSearch(){const btn=q('#searchBtn'),input=q('#searchInput');if(!btn||!input)return;btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();buildSearch(input.value.trim())},true);input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();buildSearch(input.value.trim())}},true);document.addEventListener('pointerdown',e=>{if(searchPanel?.classList.contains('open')&&!e.target.closest('.v080-search-panel,#searchBtn,#searchInput'))closeSearch()},true)}
function installLayoutPresets(){const settings=q('#settings');if(!settings||q('#v080LayoutFieldset'))return;const fs=document.createElement('fieldset');fs.id='v080LayoutFieldset';fs.innerHTML='<legend>图文布局预设</legend><div class="v080-layout-presets"><button type="button" data-preset="text">正文优先</button><button type="button" data-preset="balanced">图文均衡</button><button type="button" data-preset="figure">图表优先</button></div><small class="v080-layout-note">只调整目录和右侧图栏宽度；手动拖动分隔线后会退出预设。</small>';settings.append(fs);const root=document.documentElement,buttons=qa('button[data-preset]',fs);function apply(name,save=true){const vw=Math.max(360,innerWidth);const values=name==='text'?{side:220,view:Math.min(390,vw*.30)}:name==='figure'?{side:220,view:Math.min(780,vw*.50)}:{side:250,view:Math.min(570,vw*.38)};motion();root.style.setProperty('--sidebar-width',values.side+'px');if(document.body.classList.contains('viewer-open'))root.style.setProperty('--viewer-width',values.view+'px');localStorage.setItem('viewer-width',String(Math.round(values.view)));buttons.forEach(b=>b.classList.toggle('active',b.dataset.preset===name));if(save)localStorage.setItem('v080-layout-preset',name)}buttons.forEach(b=>b.onclick=()=>apply(b.dataset.preset));const saved=localStorage.getItem('v080-layout-preset');if(saved)apply(saved,false);['#leftResizeHandle','#rightResizeHandle'].forEach(sel=>q(sel)?.addEventListener('pointerdown',()=>{localStorage.removeItem('v080-layout-preset');buttons.forEach(b=>b.classList.remove('active'))},true))}
function installPanelFocus(){document.addEventListener('click',e=>{const head=e.target.closest('#v6StudyDoc .v6-panel>h3');if(!head||e.target.closest('.term-pop,.user-annotation'))return;if(getSelection()?.toString())return;const panel=head.closest('.v6-panel'),doc=q('#v6StudyDoc');const already=panel.classList.contains('v080-panel-focused');qa('.v6-panel',doc).forEach(x=>x.classList.remove('v080-panel-focused'));doc.classList.toggle('v080-panel-focus-mode',!already);if(!already)panel.classList.add('v080-panel-focused')},true);document.addEventListener('change',e=>{if(e.target?.id==='v6StudySelect'){q('#v6StudyDoc')?.classList.remove('v080-panel-focus-mode');qa('#v6StudyDoc .v080-panel-focused').forEach(x=>x.classList.remove('v080-panel-focused'))}},true)}
function installImagePolicy(){qa('.figure-card img,.table-card img').forEach((img,i)=>{if(i>1)img.loading='lazy';img.decoding='async'})}
function boot(){const review=runReview();installMotionHooks();installImagePolicy();installLayoutPresets();installPanelFocus();if(review.passed)installSearch();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
